server:
  port: 8053

dubbo:
  application:
    name: boot-consumer
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  #monitor:
    #protocol: registy

rocketmq:
  name-server: 127.0.0.1:9876 # 自己的RocketMQ服务地址
  producer:
    send-message-timeout: 300000
    group: my-group